version: "3.5"
services:
  pi-hole:
    build:
      context: .
      args:
        - UPSTREAM_VERSION=2025.03.0
    image: pi-hole.dnp.dappnode.eth:0.1.0
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "67:67/udp"
      - "123:123/udp"
    environment:
      TZ: 'Europe/Madrid'
      FTLCONF_webserver_api_password: ''
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - data:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
volumes:
  data: {}